# Generated by Django 5.2.4 on 2025-09-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('params_json', models.JSONField()),
                ('mode', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('pro-forma', 'Pro-Forma')], max_length=20)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['hash', 'timestamp'], name='risk_calcul_hash_0d27d6_idx')],
            },
        ),
    ]
