# Generated by Django 5.2.4 on 2025-10-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_calculator', '0002_accesspassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, help_text='Optional description for this password', max_length=255)),
            ],
            options={
                'verbose_name': 'Access Password',
                'verbose_name_plural': 'Access Passwords',
            },
        ),
        migrations.DeleteModel(
            name='AccessPassword',
        ),
    ]
