# Generated by Django 5.2.4 on 2025-10-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_calculator', '0003_passwordaccess_delete_accesspassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordaccess',
            name='last_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
