# Generated by Django 5.2.4 on 2025-11-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_calculator', '0004_passwordaccess_last_revoked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='actual_params_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['timestamp'], name='risk_calcul_timesta_eab871_idx'),
        ),
    ]
