# Generated by Django 5.2.4 on 2025-11-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_calculator', '0005_snapshot_actual_params_json_alter_snapshot_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='snapshot',
            name='risk_calcul_timesta_eab871_idx',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='actual_params_json',
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
